CELT_HEAD = \
libopus/celt/arch.h \
libopus/celt/bands.h \
libopus/celt/celt.h \
libopus/celt/cpu_support.h \
libopus/include/opus_types.h \
libopus/include/opus_defines.h \
libopus/include/opus_custom.h \
libopus/celt/cwrs.h \
libopus/celt/ecintrin.h \
libopus/celt/entcode.h \
libopus/celt/entdec.h \
libopus/celt/entenc.h \
libopus/celt/fixed_debug.h \
libopus/celt/fixed_generic.h \
libopus/celt/float_cast.h \
libopus/celt/_kiss_fft_guts.h \
libopus/celt/kiss_fft.h \
libopus/celt/laplace.h \
libopus/celt/mathops.h \
libopus/celt/mdct.h \
libopus/celt/mfrngcod.h \
libopus/celt/modes.h \
libopus/celt/os_support.h \
libopus/celt/pitch.h \
libopus/celt/celt_lpc.h \
libopus/celt/x86/celt_lpc_sse.h \
libopus/celt/quant_bands.h \
libopus/celt/rate.h \
libopus/celt/stack_alloc.h \
libopus/celt/vq.h \
libopus/celt/static_modes_float.h \
libopus/celt/static_modes_fixed.h \
libopus/celt/static_modes_float_arm_ne10.h \
libopus/celt/static_modes_fixed_arm_ne10.h \
libopus/celt/arm/armcpu.h \
libopus/celt/arm/fixed_armv4.h \
libopus/celt/arm/fixed_armv5e.h \
libopus/celt/arm/fixed_arm64.h \
libopus/celt/arm/kiss_fft_armv4.h \
libopus/celt/arm/kiss_fft_armv5e.h \
libopus/celt/arm/pitch_arm.h \
libopus/celt/arm/fft_arm.h \
libopus/celt/arm/mdct_arm.h \
libopus/celt/mips/celt_mipsr1.h \
libopus/celt/mips/fixed_generic_mipsr1.h \
libopus/celt/mips/kiss_fft_mipsr1.h \
libopus/celt/mips/mdct_mipsr1.h \
libopus/celt/mips/pitch_mipsr1.h \
libopus/celt/mips/vq_mipsr1.h \
libopus/celt/x86/pitch_sse.h \
libopus/celt/x86/vq_sse.h \
libopus/celt/x86/x86cpu.h
