SILK_HEAD = \
libopus/silk/debug.h \
libopus/silk/control.h \
libopus/silk/errors.h \
libopus/silk/API.h \
libopus/silk/typedef.h \
libopus/silk/define.h \
libopus/silk/main.h \
libopus/silk/x86/main_sse.h \
libopus/silk/PLC.h \
libopus/silk/structs.h \
libopus/silk/tables.h \
libopus/silk/tuning_parameters.h \
libopus/silk/Inlines.h \
libopus/silk/MacroCount.h \
libopus/silk/MacroDebug.h \
libopus/silk/macros.h \
libopus/silk/NSQ.h \
libopus/silk/pitch_est_defines.h \
libopus/silk/resampler_private.h \
libopus/silk/resampler_rom.h \
libopus/silk/resampler_structs.h \
libopus/silk/SigProc_FIX.h \
libopus/silk/x86/SigProc_FIX_sse.h \
libopus/silk/arm/biquad_alt_arm.h \
libopus/silk/arm/LPC_inv_pred_gain_arm.h \
libopus/silk/arm/macros_armv4.h \
libopus/silk/arm/macros_armv5e.h \
libopus/silk/arm/macros_arm64.h \
libopus/silk/arm/SigProc_FIX_armv4.h \
libopus/silk/arm/SigProc_FIX_armv5e.h \
libopus/silk/arm/NSQ_del_dec_arm.h \
libopus/silk/arm/NSQ_neon.h \
libopus/silk/fixed/main_FIX.h \
libopus/silk/fixed/structs_FIX.h \
libopus/silk/fixed/arm/warped_autocorrelation_FIX_arm.h \
libopus/silk/fixed/mips/noise_shape_analysis_FIX_mipsr1.h \
libopus/silk/fixed/mips/warped_autocorrelation_FIX_mipsr1.h \
libopus/silk/float/main_FLP.h \
libopus/silk/float/structs_FLP.h \
libopus/silk/float/SigProc_FLP.h \
libopus/silk/mips/macros_mipsr1.h \
libopus/silk/mips/NSQ_del_dec_mipsr1.h \
libopus/silk/mips/sigproc_fix_mipsr1.h
